name: Automerge Dependabot

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PRs
        uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file-path: '.github/auto-merge.yml'
          merge-method: 'squash'
          wait-for-checks: 'true'
          max-wait-time: '3600'
